on: [push, pull_request]
name: CI
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Modules tidy
      run: |
        go mod tidy
        if [[ -n $(git status --porcelain) ]]; then echo "Please fix the issues with go mod tidy"; exit 1; fi
    - name: Lint
      run: |
        go vet ./...
        gofmt -l -s -w .
        if [[ -n $(git status --porcelain) ]]; then echo "Please fix the issues with gofmt"; exit 1; fi
    - name: Test
      run: go test -v ./...
    - name: Build
      run: go build ./cmd/perseus
